.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - $TARGET_DIR/**/*
          - modules/**/*

stages:
  - deploy-stage
  - deploy-prod

aws-stag-us:
  stage: deploy-stage
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_STAGE
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_STAGE
    TARGET_DIR: "aws-stag"
    EXTRA_ARGS: "-var-file=../terraform-us.tfvars"
    WORKSPACE_NAME: "aws-stag-us"
  trigger:
    include:
      - local: ".workspace-deployment.yml"
    strategy: depend
  rules:
    - !reference [.default_rules, rules]

aws-stag-eu:
  stage: deploy-stage
  variables:
    TARGET_DIR: "aws-stag"
    EXTRA_ARGS: "-var-file=../terraform-eu.tfvars"
    WORKSPACE_NAME: "aws-stag-eu"
    # Optional set Terraform workspace
    TERRAFORM_WORKSPACE_NAME: "staging"
    # Optional profiles with their credentials
    AWS_PROFILES: |
      {
        "aws-stag-eu": {
          "key": "$AWS_ACCESS_KEY_ID_STAGE",
          "secret": "$AWS_SECRET_ACCESS_KEY_STAGE",
          "region": "us-east-1"
        }
      }

  trigger:
    include:
      - local: ".workspace-deployment.yml"
    strategy: depend
  rules:
    - !reference [.default_rules, rules]

aws-prod:
  stage: deploy-prod
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_PROD
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_PROD
    TF_VAR_bucket_name: "production-bucket-firefly-gitlab-pipeline"
    TARGET_DIR: "aws-prod"
  trigger:
    include:
      - local: ".workspace-deployment.yml"
    strategy: depend
  rules:
    - !reference [.default_rules, rules]
